### ISSUE TITLE
Request: Lieblingsklub

### ISSUE THREAD

**Issue by Maja61** [oweitman/ioBroker.openligadb#1]
Hallo,

habe folgende Anpassungswünsche: 

- Implementierung der Auswahl eines Lieblingsklubs in der Instanzkonfiguration

- Implementierung der Option "Highlight des Lieblingsklubs" in der Instanzkonfiguration

daraus resultierend:

- Ein Widget mit den kommenden X Spielen des Lieblingsklubs (wobei X auch gleich in der Konfig mit ausgewählt werden könnte)

- Highlight des Lieblingsklubs in den Widgets Spieltag und Tabelle (evtl mit Schriftart = bold oder so)

siehe auch [Forum](https://forum.iobroker.net/topic/29506/test-adapter-openligadb-v0-0-x/11)

**Comment by oweitman** [comment]
müsste mit dem heutigen update alle neuen features hinzugefügt sein.
bitte testen
