### ISSUE TITLE
certificate has expired

### ISSUE THREAD

**Issue by meistermopper** [oweitman/ioBroker.openligadb#15]
JS-Controller: 3.3.18
Adapter version: 1.1.0

I recently got this error message when the adapter restarts.

<html><body>

openligadb.0 | 2021-09-30 10:20:32.403 | error | certificate has expired
-- | -- | -- | --
openligadb.0 | 2021-09-30 10:20:32.402 | error | certificate has expired
openligadb.0 | 2021-09-30 10:20:32.400 | error | certificate has expired
openligadb.0 | 2021-09-30 10:20:32.397 | error | certificate has expired
openligadb.0 | 2021-09-30 10:20:32.397 | error | certificate has expired
openligadb.0 | 2021-09-30 10:20:32.390 | error | certificate has expired
openligadb.0 | 2021-09-30 10:20:32.387 | error | certificate has expired
openligadb.0 | 2021-09-30 10:20:32.386 | error | certificate has expired
openligadb.0 | 2021-09-30 10:10:32.391 | error | certificate has expired
openligadb.0 | 2021-09-30 10:10:32.391 | error | certificate has expired
openligadb.0 | 2021-09-30 10:10:32.387 | error | certificate has expired
openligadb.0 | 2021-09-30 10:10:32.385 | error | certificate has expired
openligadb.0 | 2021-09-30 10:10:32.383 | error | certificate has expired
openligadb.0 | 2021-09-30 10:10:32.381 | error | certificate has expired
openligadb.0 | 2021-09-30 10:10:32.377 | error | certificate has expired
openligadb.0 | 2021-09-30 10:10:32.375 | error | certificate has expired

</body>
</html>

Since yesterday I have installed nodejs 14.18.0.
However, I don't know if this is the cause of the error message.

Best regards
Thomas

**Comment by oweitman** [comment]
resolved after some hours.
i think that was the cause
https://www.heise.de/news/Let-s-Encrypt-Zertifikate-Ruckler-am-30-September-moeglich-6201155.html
