### ISSUE TITLE
Delete league /Season in Instance don't delete the ioBroker Objects

### ISSUE THREAD

**Issue by mcuiobroker** [oweitman/ioBroker.openligadb#171]
The ioBroker objects are not deleted, when I delete the league / season.
bl1 / 2021 <- deleted in the instance Config, but won't delete the objects. Must delete them manually.
bl1 / 2022

**Comment by oweitman** [comment]
yes, this is intended.
if you remove a league from the configuration, the adapter didnt request this league data any more.
maybe you want to save the data for historical reasons
