### ISSUE TITLE
Fehlermeldung bei Abfrage der BL2-Daten

### ISSUE THREAD

**Issue by RaBu60** [oweitman/ioBroker.openligadb#387]
Hallo,
ich bekomme seit einigen Tagen folgende Meldung im Log:

`Request Failed. Status Code: 301 www.openligadb.de/api/getgoalgetters/bl2/2023`
`Request Failed. Status Code: 301 www.openligadb.de/api/getbltable/bl2/2023`
`Request Failed. Status Code: 301 www.openligadb.de/api/getcurrentgroup/bl2`
`Request Failed. Status Code: 301 www.openligadb.de/api/getmatchdata/bl2/2023`

Mit anderen Ergebnissen verhält es sich genauso.
Wenn ich eine der URLs in einem Browser öffne, bekomme ich die Meldung, dass die Seite nicht gefunden werden kann.

**Comment by CKMartens** [comment]
Die API URL hat sich geändert. 
Workaround bis hier geändert wurde:
in der Datei lib/openligadbserver.js die Zeilen
`    const api_ep_gettable       = "https://www.openligadb.de/api/getbltable/%LEAGUE%/%SEASON%";
    const api_ep_actplayday     = "https://www.openligadb.de/api/getmatchdata/%LEAGUE%";
    const api_ep_allmatches     = "https://www.openligadb.de/api/getmatchdata/%LEAGUE%/%SEASON%";
    const api_ep_actgroup       = "https://www.openligadb.de/api/getcurrentgroup/%LEAGUE%";
    //const api_ep_nextgame       = "https://www.openligadb.de/api/getnextmatchbyleagueteam/%LEAGUEID%/%TEAMID%";
    //const api_ep_allteams       = "https://www.openligadb.de/api/getavailableteams/%LEAGUE%/%SEASON%";
    const api_ep_goalgetter     = "https://www.openligadb.de/api/getgoalgetters/%LEAGUE%/%SEASON%";`

ändern in 

`    const api_ep_gettable       = "https://api.openligadb.de/getbltable/%LEAGUE%/%SEASON%";
    const api_ep_actplayday     = "https://api.openligadb.de/getmatchdata/%LEAGUE%";
    const api_ep_allmatches     = "https://api.openligadb.de/getmatchdata/%LEAGUE%/%SEASON%";
    const api_ep_actgroup       = "https://api.openligadb.de/api/getcurrentgroup/%LEAGUE%";
    //const api_ep_nextgame       = "https://api.openligadb.de/getnextmatchbyleagueteam/%LEAGUEID%/%TEAMID%";
    //const api_ep_allteams       = "https://api.openligadb.de/getavailableteams/%LEAGUE%/%SEASON%";
    const api_ep_goalgetter     = "https://api.openligadb.de/getgoalgetters/%LEAGUE%/%SEASON%";`

**Comment by oweitman** [comment]
Der Adapter wurde mit der Version 1.3.0 angepasst.
Leider reichte die Änderung der Adresse allein nicht, 
da openligadb sich entschieden hat sämtliche Attributnamen von erster Buchstabe in Groß in erster Buchstabe in klein zu ändern.

**Comment by Dtrieb** [comment]
> Der Adapter wurde mit der Version 1.3.0 angepasst. Leider reichte die Änderung der Adresse allein nicht, da openligadb sich entschieden hat sämtliche Attributnamen von erster Buchstabe in Groß in erster Buchstabe in klein zu ändern. Bitte testen

Sieht so aus als geht die Version 1.3.0 - Bisher noch keinen Fehler gehabt.

**Comment by oweitman** [comment]
behoben in Version 1.3.0
