### ISSUE TITLE
Objekt currgameday undefined

### ISSUE THREAD

**Issue by Helmut1895** [oweitman/ioBroker.openligadb#401]
Hallo zusammen, 
der Adapter läuft soweit, bis auf die Anzeige der Spieltage. Die Abfrage über die Url: https://api.openligadb.de/getmatchdata/bl2/2023 liefert aber Daten. Hängt das damit zusammen, dass das Objekt currgameday undefined ist?

**Comment by oweitman** [comment]
Wurde in der Version 1.3.1 behoben
