### ISSUE TITLE
Issues from Pullrequest

### ISSUE THREAD

**Issue by oweitman** [oweitman/ioBroker.openligadb#413]
@oweitman

First of all - THANK YOU for the time and effort you spend to maintain this adapter.

Sorry to say, but the adapter currently does no longer pass standard tests. Fixing the following issues and creating a new release (as some fixes will not get into the release otherwise) is required before updateing the release at stable repository:

The following issues reported by adapter checker must be fixed:

 ❗ [E160] "admin" is not allowed in common.dependencies
 ❗ [E606] Current adapter version 1.3.4 not found in [README.md](https://github.com/oweitman/ioBroker.openligadb/blob/master/README.md)
 ❗ [E605] No actual year found in copyright. Please add "Copyright (c) 2023 oweitman [oweitman@gmx.de](mailto:oweitman@gmx.de)" at the end of [README.md](https://github.com/oweitman/ioBroker.openligadb/blob/master/README.md)
 ❗ [E701] No actual year found in LICENSE. Please add "Copyright (c) 2023 oweitman [oweitman@gmx.de](mailto:oweitman@gmx.de)" at the start of LICENSE
 👀 [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
 👀 [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
 👀 [W170] "common.keywords" should not contain "iobroker, adapter, smart home" [io-package.json](https://github.com/oweitman/ioBroker.openligadb/blob/master/io-package.json)
 👀 [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn) (at least german and english is mandatory)
In addition the following issues must be fixed:

 adapt testing to supported node releases

As node 12 and 14 are end of life and will no longer be supported by js-controller 5.x, remove node 14.x tests from matrix
Tests for node 16 is mandatory unless you require node 18 and higher.
Tests for node 18 is mandatory as many users already use node 18 and node 16 will be eol and deprected Q3/2023.
Consider adding node 20 tests unless you already know incompatibilities.

So the recommended testmatrix is [16.x, 18.x, 20.x],

 standard github tests are mandatory

Its mandatore that standard github tests (wiorkflow test-and-release.yml) is present and all tests pass.

In addiotn the following suggestions apply:

 consider updating adapter dependencies

Due to outdated / failint test environmenzt dependabot automerges have been stalled. As you will be creating a new release, check if its applicable to update dependencies together with this step.

Finally I would like to ask whther default logging level "debug" is really required. Most likely the default log level should be info. (But this is an info only and will not block update at stable repo)

**Comment by oweitman** [comment]
the adapter is updated to v1.4.6
adaper checker dont show any errrors or warnings
automatic github test and npm deployment dont have errors

after community test the version can be added to stable repo

**Comment by mcm1957** [comment]
Thanks for fixing the issues.
Please update adapter-core to 3.1.4 too. See https://github.com/oweitman/ioBroker.openligadb/issues/601
