### ISSUE TITLE
Please update README.md, update dependencies and update test-and.release workflow

### ISSUE THREAD

**Issue by mcm1957** [oweitman/ioBroker.openligadb#575]
Please add complete changelog to README.md. Users should be able to resd what has changes between last stable and current release

In addition please
- update dependencies, at least iobroker/testing and adapter-code should be updated
- update test-and-release workflow to use node 18.x/20.x
- add engines: node >= 18 clause to package.json
- correct dependencies at io-pacakge.json
  - js-controller should request at least 4.x.x, recommended is 5.0.19
  - admin must be listed as globalDependencies (and not as dependencies) and reuire at least admin 5, recommende is 6.13.16

**Comment by oweitman** [comment]
should be fixed with v1.4.6
