### ISSUE TITLE
Please confirm functionality of 1.2.4

### ISSUE THREAD

**Issue by mcm1957** [oweitman/ioBroker.openligadb#576]
The current stable verion of this adapter is 1.2.4

Please give some feedback and let us know if current stable release 1.2.4 is fully functionally or the adapter is working only when using newer release currently not avaialbal at stable repository. According toi statements at forum versions < 1.3.4 do NOT work any more.

**If there is no reaction / statemengt until 15.5.2024 release 1.2.4 will be removed from stable repository.**

**Comment by oweitman** [comment]
https://github.com/oweitman/ioBroker.openligadb/issues/413#issuecomment-2143833636
