### ISSUE TITLE
Please update adapter-core to 3.1.4 to avoid problems with js-controller 6

### ISSUE THREAD

**Issue by mcm1957** [oweitman/ioBroker.openligadb#601]
**Please update @iobroker/adapter-core to 3.1.4** to avoid potential problems with js-controller 6:

[E033] @iobroker/adapter-core 2.6.7 specified. 3.1.4 is required as minimum, 3.1.4 is recommended. Please update dependencies at package.json

---

Thanks for fixing all other things. This check is not yet available at the web based checker but only at repository update and at commandline checker. You can execute the most up to date version of the checker by running 

`npx @iobroker/repochecker https://github.com/oweitman/ioBroker.openligadb`

Thre was a PR to fix this already:
https://github.com/oweitman/ioBroker.openligadb/pull/599

But you closed it without merging for an unknown reason.

**Comment by oweitman** [comment]
fixed
